### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: InvalidInvoice

### ISSUE THREAD

**Issue by MGTHEBOSS** [RadarTech/redshift-monorepo#82]
Hi,

We would like to use the package, `@radar/redshift.js` in a project. We are testing it on glitch right now. We are getting the above mentioned error. Please resolve the issue as soon as possible. 

Please see the code in server.js below.

```
// server.js
// where your node app starts

// init project
const express = require("express");
const app = express();

// we've started you off with Express,
// but feel free to use whatever libs or frameworks you'd like through `package.json`.

// http://expressjs.com/en/starter/static-files.html
app.use(express.static("public"));

// http://expressjs.com/en/starter/basic-routing.html
app.get("/", function(request, response) {
    response.sendFile(__dirname + "/views/index.html");
});

// listen for requests :)
const listener = app.listen(process.env.PORT, function() {
    console.log("Your app is listening on port " + listener.address().port);
});

var redshiftJs = require("@radar/redshift.js")
async function f1() {
    const client = new redshiftJs.WebSocketClient();
    await client.connect();
    const quote = await client.requestQuote({
        market: redshiftJs.Market.BTC_LBTC, // bitcoin <-> lightning bitcoin
        invoice: 'BOLT-compatible-invoice',
        refundAddress: 'P2(W)PKH-address',
    });

}

f1();
```

Please see the log below.

```
a few seconds ago

🍍🏍 Your app is listening on port 3000

10:55 AM

(node:1657) UnhandledPromiseRejectionWarning: Error: InvalidInvoice

10:55 AM

    at Promise (/rbd/pnpm-volume/f6dcb3a0-a644-4d8a-9d6a-bc1189355b85/node_modules/.registry.npmjs.org/@radar/redshift-api-client/0.2.2/node_modules/@radar/redshift-api-client/dist/clients/websocket-client.js:78:35)

10:55 AM

    at new Promise (<anonymous>)

10:55 AM

    at WebSocketClient.<anonymous> (/rbd/pnpm-volume/f6dcb3a0-a644-4d8a-9d6a-bc1189355b85/node_modules/.registry.npmjs.org/@radar/redshift-api-client/0.2.2/node_modules/@radar/redshift-api-client/dist/clients/websocket-client.js:67:20)

10:55 AM

    at Generator.next (<anonymous>)

10:55 AM

    at /rbd/pnpm-volume/f6dcb3a0-a644-4d8a-9d6a-bc1189355b85/node_modules/.registry.npmjs.org/@radar/redshift-api-client/0.2.2/node_modules/@radar/redshift-api-client/dist/clients/websocket-client.js:7:71

10:55 AM

    at new Promise (<anonymous>)

10:55 AM

    at __awaiter (/rbd/pnpm-volume/f6dcb3a0-a644-4d8a-9d6a-bc1189355b85/node_modules/.registry.npmjs.org/@radar/redshift-api-client/0.2.2/node_modules/@radar/redshift-api-client/dist/clients/websocket-client.js:3:12)

10:55 AM

    at WebSocketClient.requestQuote (/rbd/pnpm-volume/f6dcb3a0-a644-4d8a-9d6a-bc1189355b85/node_modules/.registry.npmjs.org/@radar/redshift-api-client/0.2.2/node_modules/@radar/redshift-api-client/dist/clients/websocket-client.js:66:16)

10:55 AM

at f1 (

:28)

10:55 AM

    at <anonymous>

10:55 AM

    at process._tickCallback (internal/process/next_tick.js:189:7)

10:55 AM

(node:1657) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

10:55 AM

(node:1657) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

We appreciate your cooperation.

**Comment by cavanmflynn** [comment]
Hey @MGTHEBOSS, this error is being thrown because an invalid invoice is being passed into the `requestQuote` method.

I'm unsure if you've replaced the invoice and refund address for the purpose of opening this issue, but `BOLT-compatible-invoice` should be replaced with a valid Lightning Bitcoin invoice (starts with `lnbc`) and `P2(W)PKH-address` should be replaced with a valid Bitcoin address.

All WebSocket client methods will throw an error if a validation fails. To avoid unhandled promise rejections, wrap your request in a try/catch:

```typescript
try {
  await client.connect();
  const quote = await client.requestQuote({
      market: redshiftJs.Market.BTC_LBTC, // bitcoin <-> lightning bitcoin
      invoice: 'BOLT-compatible-invoice', // replace with lightning bitcoin invoice
      refundAddress: 'P2(W)PKH-address',  // replace with bitcoin address
  });
} catch (error) {
  // Handle the error
}
```
